Popup
Edward-Kabue/Portfolio-mv pull request #15
Opened 2022-03-02 13:11 UTC by Edward-Kabue

## Add popup by rendering dynamically

2022-03-02 14:03 UTC, ShoiraTa requested changes
Hi team,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- JS loading data dynamically ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-02 14:03 UTC, ShoiraTa commented on index.html
> +                    <p class="article-e">
- [ ]  Based on one of the requirements, the popup follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, tests, margins). Please make sure that margins and paddings match with the design you selected. Currently the modal looks to be broken: 

Your design  | Figma design
------------- | -------------
<img width="860" alt="Screenshot 2022-03-02 at 17 43 39" src="https://user-images.githubusercontent.com/77038610/156373121-7a64ca61-53ee-4bc2-916f-ba82472d5d4c.png"> | <img width="576" alt="Screenshot 2022-03-02 at 17 44 02" src="https://user-images.githubusercontent.com/77038610/156373181-0c022c22-aaa0-45b0-81f3-c24cdbad779c.png">

> More specifically: 

- [ ]  I recommend to hide the body, so that users could see only the popup window. Currently, I can scroll the window and see the body content.
- [ ] Please make sure to add all the images that should be displayed in the modal. In current case the main image source is `src="./images/modal.png"`, but it is broken because in images folder there is no  `modal.png` same with `live.svg`. 
- [ ] Below `Tonic`  make sure to add missing listings:

Your design  | Figma design
------------- | -------------
<img width="225" alt="Screenshot 2022-03-02 at 17 52 06" src="https://user-images.githubusercontent.com/77038610/156374533-3c05ba78-7825-47d9-8f34-21f6820f943e.png">  | <img width="277" alt="Screenshot 2022-03-02 at 17 51 40" src="https://user-images.githubusercontent.com/77038610/156374482-924a1ebb-fae8-446a-93ef-9673d85b0c7f.png">

- [ ] After fixing the image rendering, kindly make sure that your design and layout matches the template in Figma.

2022-03-02 14:03 UTC, ShoiraTa commented on index.html
> +                                class="bi bi-github source"></i></button>
- [ ] Please kindly add horisontal line between frameworks and buttons, add proper margins and add more frameworks, and align frameworks to the left as provided in Figma

Your design  | Figma design
------------- | -------------
<img width="243" alt="Screenshot 2022-03-02 at 17 56 37" src="https://user-images.githubusercontent.com/77038610/156375318-329da2ea-d5b0-4fa3-b564-7f2c6d9f66b9.png"> | <img width="264" alt="Screenshot 2022-03-02 at 17 56 21" src="https://user-images.githubusercontent.com/77038610/156375269-f6237782-c010-4890-9a64-7749a70bfd28.png">

2022-03-02 14:03 UTC, ShoiraTa commented on index.html
> +                    <ul class="built-with-e">
- [ ] Please make sure that the mobile view matches the design provieded in Figma:

Your design  | Figma design
------------- | -------------
<img width="258" alt="Screenshot 2022-03-02 at 18 01 18" src="https://user-images.githubusercontent.com/77038610/156376128-019790a9-28fb-411b-9f7e-651172dc21c8.png"> | <img width="279" alt="Screenshot 2022-03-02 at 18 00 48" src="https://user-images.githubusercontent.com/77038610/156376039-3fe247ac-c44f-42b9-8164-96ba82e54cdc.png">

2022-03-03 11:08 UTC, micheaol requested changes
Hi @Edward-Kabue , 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-03 11:08 UTC, micheaol commented on index.html
> +                    <ul class="built-with-e">
As requested by the previous code reviewer, please ensure that the mobile view matches the design provided in Figma:

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/156550818-8d3dc898-a75b-4d17-9445-29bd8fc71199.png) | ![image](https://user-images.githubusercontent.com/10332499/156550959-9432bdc7-6ae4-4ce4-b838-06ac31c56850.png)

2022-03-03 11:08 UTC, micheaol commented on index.html
> +                    <p class="article-e">
As requested by the previous code reviewer, please ensure that the popup follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, tests, margins).

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/156551676-a7b56ef3-2ee8-4750-a59b-b1235fd73edf.png) | ![image](https://user-images.githubusercontent.com/10332499/156551777-db12d744-94d2-4c00-a812-ab0f27c2c011.png)

2022-03-03 11:08 UTC, micheaol commented on index.html
> +                    <p class="article-e">
As requested by the previous code reviewer, please ensure that the `Tonic`  listings are added and aligned according to the project requirement.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/156552548-3896b7c1-518a-4810-9843-dbe84b5845fe.png) |  ![image](https://user-images.githubusercontent.com/10332499/156552607-9e565f06-c37d-43fa-81c6-c5c88179d4d9.png)

2022-03-03 11:08 UTC, micheaol commented on index.html
> +                                class="bi bi-github source"></i></button>
As requested by the previous code reviewer, please ensure that the popup follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colors, images, tests, margins).

2022-03-03 15:42 UTC, brytebee approved these changes
Hi, @Edward-Kabue 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 15:49 UTC, merged